# Generated by Django 4.2.16 on 2025-05-29 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_is_sale_product_sale_price_alter_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='frist_name',
            new_name='first_name',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 5, 29, 16, 4, 9, 53277)),
        ),
    ]
