# Generated by Django 4.2.16 on 2025-05-30 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_frist_name_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 5, 30, 16, 17, 0, 791992)),
        ),
    ]
